Coreaudio
Superbowl-tibet/SwiftBowl pull request #56
Opened 2017-03-20 21:35 UTC by susan335

# AudioEngine プロトコルの変更

- 音量を変化させるパラメータを非推奨に
`@available(*, deprecated, message: "")
var speed: Float { get set }`

- 音色を変化させるパラメータを削除
` var sound: Sound { get set }`

- 高い音色の音量を変化させるパラメータを追加
`var highToneVolume: Float { get set }`

- 低いい音色の音量を変化させるパラメータを追加
`var lowToneVolume: Float { get set }`

# 音源ファイルについて
従来までは音源ループの境目でノイズがのるため、2~3分の長尺ファイルを使用していました。
ループの境目のノイズ除去に成功したため、短い尺のファイルに置き換えました。
短尺ファイルはフェードイン・フェードアウトするものを二重に鳴らし、オフセットさせてます。
なので、今までとは違う揺らぎ感があるかもかも。

2017-03-20 21:37 UTC, susan335 commented
レビューア悩んだのぜ全員追加させてもらいました (^^;

2017-03-21 03:21 UTC, mitsuyoshi-yamazaki requested changes
ログ（print文）とでかいコメントブロックは消しませんか
残っててもいいけど `// TODO:` にするとかいつのタイミングで復活させるとか書いておいてください

2017-03-21 03:22 UTC, mitsuyoshi-yamazaki commented
AudioEngineの中身はわかりませんが落ちずに実行できてるからいいのではないかと

2017-03-21 03:46 UTC, hiroaki14358 commented on SuperBowl/AudioTools/AudioEngine.swift
> +    @available(*, deprecated, message: "")
この@availableは「もうspeedプロパティは使わないよー」っていう意味でいいの？

2017-03-21 03:57 UTC, hiroaki14358 reviewed
コードのお勉強させていただきました。来週からObj-Cも触るようなので、復習も兼ねながら。PlayがstartGraphとかになるのが面白いね。

2017-03-24 09:20 UTC, MMizogaki commented
@susan335 おおおおお！

2017-03-24 09:23 UTC, merged

2017-03-24 09:25 UTC, MMizogaki commented
![thumbnail](https://cloud.githubusercontent.com/assets/11548811/24288056/4e51e40e-10bf-11e7-9022-1b7289680489.jpg)

2017-03-25 03:41 UTC, susan335 commented on SuperBowl/AudioTools/AudioEngine.swift
> +    @available(*, deprecated, message: "")
そうです！ deprecatedとしているので、このプロパティを読んでいる箇所はワーニングが出ます。
完全に消してしまうとコンパイルエラーになるので、一旦このように対処しました。

2017-03-25 03:42 UTC, susan335 commented
@mitsuyoshi-yamazaki レビューありがとうございます！修正まで少々お待ちください...

2017-03-25 23:31 UTC, hiroaki14358 commented on SuperBowl/AudioTools/AudioEngine.swift
> +    @available(*, deprecated, message: "")
なるほどー。消すと不都合があるプロパティはこうやって残しつつ、バグのもとにならないようにするんだね。ありがとー。